// <auto-generated />
namespace BlowTrial.Migrations.TrialData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UnsuccessfulFollowUpErrors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnsuccessfulFollowUpErrors));
        
        string IMigrationMetadata.Id
        {
            get { return "201611232250302_UnsuccessfulFollowUpErrors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
