// <auto-generated />
namespace BlowTrial.Migrations.TrialData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AllocationBlockIdNotNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllocationBlockIdNotNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201407280249147_AllocationBlockIdNotNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
