// <auto-generated />
namespace BlowTrial.Migrations.TrialData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class InitialTrialData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialTrialData));
        
        string IMigrationMetadata.Id
        {
            get { return "201403062253529_InitialTrialData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
