// <auto-generated />
namespace BlowTrial.Migrations.TrialData
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CurrentlyEnrolling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrentlyEnrolling));
        
        string IMigrationMetadata.Id
        {
            get { return "201501112221341_CurrentlyEnrolling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
