// <auto-generated />
namespace BlowTrial.Migrations.Membership
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DefaultAllocationGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefaultAllocationGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201407032252231_DefaultAllocationGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
