//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlowTrial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlowTrial.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil (Control &amp; BCG Brazil).
        /// </summary>
        public static string AllocationGroups_Brazil2Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_Brazil2Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish 2 Arm (Control &amp; Danish BCG).
        /// </summary>
        public static string AllocationGroups_Danish2Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_Danish2Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Signal (Control &amp; Green Signal BCG).
        /// </summary>
        public static string AllocationGroups_GreenSignal2Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_GreenSignal2Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India 2 arm (Control &amp; BCG India).
        /// </summary>
        public static string AllocationGroups_India2Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_India2Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India 3 arm (Control, BCG India &amp; Danish).
        /// </summary>
        public static string AllocationGroups_India3ArmBalanced {
            get {
                return ResourceManager.GetString("AllocationGroups_India3ArmBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India 3 arm (catch up assignnment).
        /// </summary>
        public static string AllocationGroups_India3ArmUnbalanced {
            get {
                return ResourceManager.GetString("AllocationGroups_India3ArmUnbalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan (Control &amp; BCG-Japan).
        /// </summary>
        public static string AllocationGroups_Japan2Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_Japan2Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda 3 arm (Control, BCG India &amp; BCG Japan).
        /// </summary>
        public static string AllocationGroups_Uganda3Arm {
            get {
                return ResourceManager.GetString("AllocationGroups_Uganda3Arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants ({0} of {1} displayed).
        /// </summary>
        public static string AllParticipantsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllParticipantsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection.
        /// </summary>
        public static string AppSettingsVM_DataCollection {
            get {
                return ResourceManager.GetString("AppSettingsVM_DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Oversight.
        /// </summary>
        public static string AppSettingsVM_DataOversight {
            get {
                return ResourceManager.GetString("AppSettingsVM_DataOversight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application purpose.
        /// </summary>
        public static string BackupDirectionViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BackupDirectionViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been recieved to update the database with information entered by a trial oversight computer. Please save any changes, and then logout or close the application..
        /// </summary>
        public static string BackupService_DBupdateRequestExplanation {
            get {
                return ResourceManager.GetString("BackupService_DBupdateRequestExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Request Received.
        /// </summary>
        public static string BackupService_DBupdateRequestHeader {
            get {
                return ResourceManager.GetString("BackupService_DBupdateRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOW Trial (BCG for low-birth-weight babies).
        /// </summary>
        public static string Blowtrial_ProjectName {
            get {
                return ResourceManager.GetString("Blowtrial_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congenital malformation.
        /// </summary>
        public static string CauseOfDeathOption_CongenitalMalformation {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_CongenitalMalformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyaline membrane disease.
        /// </summary>
        public static string CauseOfDeathOption_HyalineMembraneDisease {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_HyalineMembraneDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infection.
        /// </summary>
        public static string CauseOfDeathOption_Infection {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_Infection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intraventricular haemorrhage (IVH).
        /// </summary>
        public static string CauseOfDeathOption_IntraventricularHaemorrhage {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_IntraventricularHaemorrhage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necrotising enterocollitis (NEC).
        /// </summary>
        public static string CauseOfDeathOption_NecrotisingEnterocollitis {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_NecrotisingEnterocollitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CauseOfDeathOption_Other {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CauseOfDeathOption_Unknown {
            get {
                return ResourceManager.GetString("CauseOfDeathOption_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory is not found.
        /// </summary>
        public static string CloudDirectory_Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("CloudDirectory_Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup interval must be between 1 minute and  1 day.
        /// </summary>
        public static string CloudDirectory_Error_IntervalOutOfRange {
            get {
                return ResourceManager.GetString("CloudDirectory_Error_IntervalOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cloud directory must be less than 1024 characters.
        /// </summary>
        public static string CloudDirectory_Error_StringLengthTooLong {
            get {
                return ResourceManager.GetString("CloudDirectory_Error_StringLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate directories.
        /// </summary>
        public static string CloudDirectoryModel_Error_DuplicateDirectory {
            get {
                return ResourceManager.GetString("CloudDirectoryModel_Error_DuplicateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 directory can be nominated at a data collecting site.
        /// </summary>
        public static string CloudDirectoryModel_Error_ExcessDirectories {
            get {
                return ResourceManager.GetString("CloudDirectoryModel_Error_ExcessDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in 1 of the selected direcories (hover mouse for details).
        /// </summary>
        public static string CloudDirectoryModel_Error_InValid {
            get {
                return ResourceManager.GetString("CloudDirectoryModel_Error_InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a direcory.
        /// </summary>
        public static string CloudDirectoryModel_Error_NoDirectories {
            get {
                return ResourceManager.GetString("CloudDirectoryModel_Error_NoDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Directory.
        /// </summary>
        public static string CloudDirectoryViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CloudDirectoryViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collecting site.
        /// </summary>
        public static string CloudDirectoryVm_DataCollectingSite {
            get {
                return ResourceManager.GetString("CloudDirectoryVm_DataCollectingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data oversight.
        /// </summary>
        public static string CloudDirectoryVm_DataReceivingSite {
            get {
                return ResourceManager.GetString("CloudDirectoryVm_DataReceivingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cloud directoy.
        /// </summary>
        public static string CloudDirectoryVm_SelectDir {
            get {
                return ResourceManager.GetString("CloudDirectoryVm_SelectDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist.
        /// </summary>
        public static string CreateCsvModel_Error_DirectoryExists {
            get {
                return ResourceManager.GetString("CreateCsvModel_Error_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.
        /// </summary>
        public static string CreateCsvModel_Error_InvalidDateFormat {
            get {
                return ResourceManager.GetString("CreateCsvModel_Error_InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If date contains a comma, dates must be in quotes or seperated by another character.
        /// </summary>
        public static string CreateCsvModel_Error_NoDateQuotes {
            get {
                return ResourceManager.GetString("CreateCsvModel_Error_NoDateQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV file.
        /// </summary>
        public static string CreateCsvVM_Title {
            get {
                return ResourceManager.GetString("CreateCsvVM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string CreateNewUserModel_Error_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("CreateNewUserModel_Error_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Investigator.
        /// </summary>
        public static string CreateNewUserViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CreateNewUserViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name is already in use.
        /// </summary>
        public static string CreateNewUserViewModel_Error_UserExists {
            get {
                return ResourceManager.GetString("CreateNewUserViewModel_Error_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccine names must be unique.
        /// </summary>
        public static string CreateNewVaccine_Duplicate {
            get {
                return ResourceManager.GetString("CreateNewVaccine_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting 6 weeks for BCG scar follow up.
        /// </summary>
        public static string DataRequiredOption_Awaiting6WeeksToElapse {
            get {
                return ResourceManager.GetString("DataRequiredOption_Awaiting6WeeksToElapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG Scar follow up due.
        /// </summary>
        public static string DataRequiredOption_AwaitingInfantScarDetails {
            get {
                return ResourceManager.GetString("DataRequiredOption_AwaitingInfantScarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting discharge, death or 28 day outcome.
        /// </summary>
        public static string DataRequiredOption_AwaitingOutcomeOr28 {
            get {
                return ResourceManager.GetString("DataRequiredOption_AwaitingOutcomeOr28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomised participants waiting BCG data.
        /// </summary>
        public static string DataRequiredOption_BcgDataRequired {
            get {
                return ResourceManager.GetString("DataRequiredOption_BcgDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed records.
        /// </summary>
        public static string DataRequiredOption_Complete {
            get {
                return ResourceManager.GetString("DataRequiredOption_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records with details missing.
        /// </summary>
        public static string DataRequiredOption_DetailsMissing {
            get {
                return ResourceManager.GetString("DataRequiredOption_DetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial follow up unsuccesful - retry awaited.
        /// </summary>
        public static string DataRequiredOption_FailedInitialContact {
            get {
                return ResourceManager.GetString("DataRequiredOption_FailedInitialContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s BCG scar details required.
        /// </summary>
        public static string DataRequiredOption_MaternalBCGScarDetails {
            get {
                return ResourceManager.GetString("DataRequiredOption_MaternalBCGScarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants over 28 days requiring outcome data.
        /// </summary>
        public static string DataRequiredOption_OutcomeRequired {
            get {
                return ResourceManager.GetString("DataRequiredOption_OutcomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be AFTER the date of birth and prior to the current date &amp; time.
        /// </summary>
        public static string Date_Error_OutOfRange {
            get {
                return ResourceManager.GetString("Date_Error_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date.
        /// </summary>
        public static string DateTime_Error_Date_DateTimeEmpty {
            get {
                return ResourceManager.GetString("DateTime_Error_Date_DateTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must not be before {0}.
        /// </summary>
        public static string DateTime_Error_Date_MustComeAfter {
            get {
                return ResourceManager.GetString("DateTime_Error_Date_MustComeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must not be after {0}.
        /// </summary>
        public static string DateTime_Error_Date_MustComeBefore {
            get {
                return ResourceManager.GetString("DateTime_Error_Date_MustComeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date is required.
        /// </summary>
        public static string DateTime_Error_DateEmpty {
            get {
                return ResourceManager.GetString("DateTime_Error_DateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [&amp; time required].
        /// </summary>
        public static string DateTime_Error_Time_DateTimeEmpty {
            get {
                return ResourceManager.GetString("DateTime_Error_Time_DateTimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time must not be before {0}.
        /// </summary>
        public static string DateTime_Error_Time_MustComeAfter {
            get {
                return ResourceManager.GetString("DateTime_Error_Time_MustComeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time must not be after {0}.
        /// </summary>
        public static string DateTime_Error_Time_MustComeBefore {
            get {
                return ResourceManager.GetString("DateTime_Error_Time_MustComeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A time is required.
        /// </summary>
        public static string DateTime_Error_TimeEmpty {
            get {
                return ResourceManager.GetString("DateTime_Error_TimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the current date and time.
        /// </summary>
        public static string DateTime_Now {
            get {
                return ResourceManager.GetString("DateTime_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string DateTime_Today {
            get {
                return ResourceManager.GetString("DateTime_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value.
        /// </summary>
        public static string DropDownList_Error_BoolNull {
            get {
                return ResourceManager.GetString("DropDownList_Error_BoolNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DropDownList_False {
            get {
                return ResourceManager.GetString("DropDownList_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Specified).
        /// </summary>
        public static string DropDownList_NotSpecified {
            get {
                return ResourceManager.GetString("DropDownList_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        public static string DropDownList_Other {
            get {
                return ResourceManager.GetString("DropDownList_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please Select).
        /// </summary>
        public static string DropDownList_PleaseSelect {
            get {
                return ResourceManager.GetString("DropDownList_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DropDownList_True {
            get {
                return ResourceManager.GetString("DropDownList_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value.
        /// </summary>
        public static string Field_Error_Empty {
            get {
                return ResourceManager.GetString("Field_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {0} characters long.
        /// </summary>
        public static string Field_Error_TooLong {
            get {
                return ResourceManager.GetString("Field_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} characters long.
        /// </summary>
        public static string Field_Error_TooShort {
            get {
                return ResourceManager.GetString("Field_Error_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reaction.
        /// </summary>
        public static string FollowUpBabyBCGReactionStatus_NoReaction {
            get {
                return ResourceManager.GetString("FollowUpBabyBCGReactionStatus_NoReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papule Only.
        /// </summary>
        public static string FollowUpBabyBCGReactionStatus_PapuleOnly {
            get {
                return ResourceManager.GetString("FollowUpBabyBCGReactionStatus_PapuleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pustule or Scar.
        /// </summary>
        public static string FollowUpBabyBCGReactionStatus_PustuleOrScar {
            get {
                return ResourceManager.GetString("FollowUpBabyBCGReactionStatus_PustuleOrScar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites must have perceptually different colours.
        /// </summary>
        public static string GetAppSettingsModel_Error_DuplicateColours {
            get {
                return ResourceManager.GetString("GetAppSettingsModel_Error_DuplicateColours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites must have distinct names.
        /// </summary>
        public static string GetAppSettingsModel_Error_DuplicateSiteName {
            get {
                return ResourceManager.GetString("GetAppSettingsModel_Error_DuplicateSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 study site must be nominated.
        /// </summary>
        public static string GetAppSettingsModel_Error_NoStudySites {
            get {
                return ResourceManager.GetString("GetAppSettingsModel_Error_NoStudySites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error with one of the study sites you specified..
        /// </summary>
        public static string GetAppSettingsModel_Error_StudySite {
            get {
                return ResourceManager.GetString("GetAppSettingsModel_Error_StudySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative values are not allowed.
        /// </summary>
        public static string Int_Error_LessThan0 {
            get {
                return ResourceManager.GetString("Int_Error_LessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than 0.
        /// </summary>
        public static string Int_Error_LessThan1 {
            get {
                return ResourceManager.GetString("Int_Error_LessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new envelope randomised patients.
        /// </summary>
        public static string MainWindow_StopComputerRandomisingCaption {
            get {
                return ResourceManager.GetString("MainWindow_StopComputerRandomisingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start computerised randomising.
        /// </summary>
        public static string MainWindow_StopEnvelopeRandomisingCaption {
            get {
                return ResourceManager.GetString("MainWindow_StopEnvelopeRandomisingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step cannot be undone. Click OK only if all patients randomised by envelope have been entered into the &apos;New Patient&apos; form..
        /// </summary>
        public static string MainWindow_StopEnvelopeRandomisingMsg {
            get {
                return ResourceManager.GetString("MainWindow_StopEnvelopeRandomisingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to BLOW trial.
        /// </summary>
        public static string MainWindowViewModel_Command_Login {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Patient.
        /// </summary>
        public static string MainWindowViewModel_Command_RegisterNewPatient {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RegisterNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewParticipants {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Violations.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewProtocolViolations {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewProtocolViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screened Patients.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewScreened {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewScreened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screened Patients.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewScreenedPatients {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewScreenedPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Data.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewSummary {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        public static string MainWindowViewModel_WorkspaceName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_WorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mask can only contain characters [0 9 # L ? A a &amp; C . &gt; &lt; ! \ &quot;].
        /// </summary>
        public static string Mask_Error_InvalidCharacters {
            get {
                return ResourceManager.GetString("Mask_Error_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mask must not be more than {0} characters long.
        /// </summary>
        public static string Mask_Error_TooLong {
            get {
                return ResourceManager.GetString("Mask_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scar.
        /// </summary>
        public static string MaternalBCGScarStatus_NoScar {
            get {
                return ResourceManager.GetString("MaternalBCGScarStatus_NoScar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scar Present.
        /// </summary>
        public static string MaternalBCGScarStatus_ScarPresent {
            get {
                return ResourceManager.GetString("MaternalBCGScarStatus_ScarPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unascertainable.
        /// </summary>
        public static string MaternalBCGScarStatus_Unascertainable {
            get {
                return ResourceManager.GetString("MaternalBCGScarStatus_Unascertainable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear data entered (without saving).
        /// </summary>
        public static string MessageBox_ConfirmClear {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBox_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG already given.
        /// </summary>
        public static string NewPatient_BCGgiven {
            get {
                return ResourceManager.GetString("NewPatient_BCGgiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG NOT given yet.
        /// </summary>
        public static string NewPatient_BCGnotGiven {
            get {
                return ResourceManager.GetString("NewPatient_BCGnotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written consent obtained.
        /// </summary>
        public static string NewPatient_ConsentObtained {
            get {
                return ResourceManager.GetString("NewPatient_ConsentObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused consent.
        /// </summary>
        public static string NewPatient_ConsentRefused {
            get {
                return ResourceManager.GetString("NewPatient_ConsentRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent status is irrelevant for this patient.
        /// </summary>
        public static string NewPatient_Error_ConsentIrrelevant {
            get {
                return ResourceManager.GetString("NewPatient_Error_ConsentIrrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter whether consent was obtained.
        /// </summary>
        public static string NewPatient_Error_ConsentRequired {
            get {
                return ResourceManager.GetString("NewPatient_Error_ConsentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient must be born BEFORE the current date &amp; time.
        /// </summary>
        public static string NewPatient_Error_DOBafterNow {
            get {
                return ResourceManager.GetString("NewPatient_Error_DOBafterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient must be less than 22 days old at the time of randomising.
        /// </summary>
        public static string NewPatient_Error_DOBtooOldToRandomise {
            get {
                return ResourceManager.GetString("NewPatient_Error_DOBtooOldToRandomise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients cannot be screened after 180 days since birth.
        /// </summary>
        public static string NewPatient_Error_DOBtooOldToScreen {
            get {
                return ResourceManager.GetString("NewPatient_Error_DOBtooOldToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestational Age must be between 24 and 43 weeks.
        /// </summary>
        public static string NewPatient_Error_InvalidGestation {
            get {
                return ResourceManager.GetString("NewPatient_Error_InvalidGestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between 0 and 6 days.
        /// </summary>
        public static string NewPatient_Error_InvalidGestationDays {
            get {
                return ResourceManager.GetString("NewPatient_Error_InvalidGestationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital identifier must be 7 digits.
        /// </summary>
        public static string NewPatient_Error_InvalidHospitalIdentifier {
            get {
                return ResourceManager.GetString("NewPatient_Error_InvalidHospitalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be between 350 and 1999 grams.
        /// </summary>
        public static string NewPatient_Error_InvalidWeight {
            get {
                return ResourceManager.GetString("NewPatient_Error_InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission diagnosis is missing.
        /// </summary>
        public static string NewPatient_Error_MissingDiagnosis {
            get {
                return ResourceManager.GetString("NewPatient_Error_MissingDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the gestational age in weeks.
        /// </summary>
        public static string NewPatient_Error_NoGA {
            get {
                return ResourceManager.GetString("NewPatient_Error_NoGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the gestational age in days.
        /// </summary>
        public static string NewPatient_Error_NoGAdaysOnly {
            get {
                return ResourceManager.GetString("NewPatient_Error_NoGAdaysOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &amp; days.
        /// </summary>
        public static string NewPatient_Error_NoGAdaysSuffix {
            get {
                return ResourceManager.GetString("NewPatient_Error_NoGAdaysSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must be {0}-{1} digits.
        /// </summary>
        public static string NewPatient_Error_PhoneNumberFormat {
            get {
                return ResourceManager.GetString("NewPatient_Error_PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A randomising envelope should not be used for this twin. Id will be auto assigned..
        /// </summary>
        public static string NewPatient_Error_TwinAndEnvelope {
            get {
                return ResourceManager.GetString("NewPatient_Error_TwinAndEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this twin is of a different gender &amp; will be randomised normally.
        /// </summary>
        public static string NewPatient_Error_TwinGenderDifferent {
            get {
                return ResourceManager.GetString("NewPatient_Error_TwinGenderDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A twin of that patient would be expected to have a gestation of {0} weeks.
        /// </summary>
        public static string NewPatient_Error_TwinGestAge {
            get {
                return ResourceManager.GetString("NewPatient_Error_TwinGestAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twins must be born within {0:n0} hours.
        /// </summary>
        public static string NewPatient_Error_TwinSeparation {
            get {
                return ResourceManager.GetString("NewPatient_Error_TwinSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string NewPatient_Gender_Female {
            get {
                return ResourceManager.GetString("NewPatient_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string NewPatient_Gender_Male {
            get {
                return ResourceManager.GetString("NewPatient_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to die within 24 hours.
        /// </summary>
        public static string NewPatient_IsLikelyDie24 {
            get {
                return ResourceManager.GetString("NewPatient_IsLikelyDie24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to survive more than 24 hours.
        /// </summary>
        public static string NewPatient_NotLikelyDie24 {
            get {
                return ResourceManager.GetString("NewPatient_NotLikelyDie24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Succesfully Randomised.
        /// </summary>
        public static string NewPatient_SuccesfullyRandomised {
            get {
                return ResourceManager.GetString("NewPatient_SuccesfullyRandomised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been randomised to the CONTROL arm with an ID of {1}..
        /// </summary>
        public static string NewPatient_ToControl {
            get {
                return ResourceManager.GetString("NewPatient_ToControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been randomised to the INTERVENTION arm with an ID of {1}..
        /// </summary>
        public static string NewPatient_ToIntervention {
            get {
                return ResourceManager.GetString("NewPatient_ToIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolment.
        /// </summary>
        public static string NewPatientModel_DateTimeEnrollment {
            get {
                return ResourceManager.GetString("NewPatientModel_DateTimeEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both weight and gender do not match the envelope number.
        /// </summary>
        public static string NewPatientModel_Error_EnvelopeDualIncorrect {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_EnvelopeDualIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gender is incorrect for that envelope.
        /// </summary>
        public static string NewPatientModel_Error_EnvelopeGenderIncorrect {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_EnvelopeGenderIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No envelope is labeled with that number.
        /// </summary>
        public static string NewPatientModel_Error_EnvelopeNotFound {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_EnvelopeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient&apos;s weight is incorrect for that envelope.
        /// </summary>
        public static string NewPatientModel_Error_EnvelopeWeightIncorrect {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_EnvelopeWeightIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id numbers for this site must be between {0} and {1}.
        /// </summary>
        public static string NewPatientModel_Error_IdOutOfRangeForSite {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_IdOutOfRangeForSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A study site must be selected for this patient.
        /// </summary>
        public static string NewPatientModel_Error_NoStudyCentre {
            get {
                return ResourceManager.GetString("NewPatientModel_Error_NoStudyCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for that envelope number have already been entered.
        /// </summary>
        public static string NewPatientViewModel_Error_EnvelopeInDb {
            get {
                return ResourceManager.GetString("NewPatientViewModel_Error_EnvelopeInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No - Transferred here after birth.
        /// </summary>
        public static string NewPatientViewModel_Option_InbornFalse {
            get {
                return ResourceManager.GetString("NewPatientViewModel_Option_InbornFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - Born in this unit.
        /// </summary>
        public static string NewPatientViewModel_Option_InbornTrue {
            get {
                return ResourceManager.GetString("NewPatientViewModel_Option_InbornTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the envelope ({0}). Click OK to continue (and a major protocol violation will be automatically logged), or click cancel and correct any errors..
        /// </summary>
        public static string NewPatientViewModel_SoftError_Envelope {
            get {
                return ResourceManager.GetString("NewPatientViewModel_SoftError_Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue despite error?.
        /// </summary>
        public static string NewPatientViewModel_SoftError_WarningMsg {
            get {
                return ResourceManager.GetString("NewPatientViewModel_SoftError_WarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centile({0:P2}).
        /// </summary>
        public static string NewPatientVM_Centile {
            get {
                return ResourceManager.GetString("NewPatientVM_Centile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string NewPatientVM_DisplayName {
            get {
                return ResourceManager.GetString("NewPatientVM_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A patient has already been enrolled with this hospital identifier.
        /// </summary>
        public static string NewPatientVM_Error_DuplicateEnrol {
            get {
                return ResourceManager.GetString("NewPatientVM_Error_DuplicateEnrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A patient has already been screened with this hospital identifier.
        /// </summary>
        public static string NewPatientVM_Error_DuplicateScreen {
            get {
                return ResourceManager.GetString("NewPatientVM_Error_DuplicateScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the study number of the enrolled twin.
        /// </summary>
        public static string NewPatientVM_Error_SiblingIdEmpty {
            get {
                return ResourceManager.GetString("NewPatientVM_Error_SiblingIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participant can be found with the specified study number.
        /// </summary>
        public static string NewPatientVM_Error_SiblingNotFound {
            get {
                return ResourceManager.GetString("NewPatientVM_Error_SiblingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string OptionMissing {
            get {
                return ResourceManager.GetString("OptionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died in hospital before 28 days.
        /// </summary>
        public static string OutcomeAt28DaysOption_DiedInHospitalBefore28Days {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_DiedInHospitalBefore28Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharged and known to have died.
        /// </summary>
        public static string OutcomeAt28DaysOption_DischargedAndKnownToHaveDied {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_DischargedAndKnownToHaveDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharged and known to have survived.
        /// </summary>
        public static string OutcomeAt28DaysOption_DischargedAndKnownToHaveSurvived {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_DischargedAndKnownToHaveSurvived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharged and likely to have survived.
        /// </summary>
        public static string OutcomeAt28DaysOption_DischargedAndLikelyToHaveSurvived {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_DischargedAndLikelyToHaveSurvived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharged before 28 days.
        /// </summary>
        public static string OutcomeAt28DaysOption_DischargedBefore28Days {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_DischargedBefore28Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpatient at 28 days.
        /// </summary>
        public static string OutcomeAt28DaysOption_InpatientAt28Days {
            get {
                return ResourceManager.GetString("OutcomeAt28DaysOption_InpatientAt28Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the date/time of discharge.
        /// </summary>
        public static string ParticipantModel_Describe_DateTimeDischarge {
            get {
                return ResourceManager.GetString("ParticipantModel_Describe_DateTimeDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient can not be alive at 28 days until the patient is 28 days of age.
        /// </summary>
        public static string ParticipantModel_Error_Alive28daysNotElapsed {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_Alive28daysNotElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby must be 6 weeks post BCG to enter scar details.
        /// </summary>
        public static string ParticipantModel_Error_BabyBCGScarPre6Weeks {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_BabyBCGScarPre6Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient cannot have a BCG papule at 28 days if he/she died before day 28.
        /// </summary>
        public static string ParticipantModel_Error_Bcg28daysDead {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_Bcg28daysDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient cannot have a BCG papule at 28 days if the 28 day outcome is unknown.
        /// </summary>
        public static string ParticipantModel_Error_Bcg28daysNoOutcome {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_Bcg28daysNoOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient cannot have a BCG papule at 28 days until they are 28 days of age.
        /// </summary>
        public static string ParticipantModel_Error_Bcg28daysNotElapsed {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_Bcg28daysNotElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details of the BCG reaction.
        /// </summary>
        public static string ParticipantModel_Error_BcgAdverseDetailRequired {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_BcgAdverseDetailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient can only have a value for BCG papule at death, discharge if one of these events has occurred.
        /// </summary>
        public static string ParticipantModel_Error_BcgNeitherDischOrDead {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_BcgNeitherDischOrDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baby&apos;s BCG reaction at follow up is required.
        /// </summary>
        public static string ParticipantModel_Error_BCGReactionRequired {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_BCGReactionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details of when the BCG was given.
        /// </summary>
        public static string ParticipantModel_Error_BcgRequiredForAdverse {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_BcgRequiredForAdverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details about the cause of death.
        /// </summary>
        public static string ParticipantModel_Error_CauseOfDeathDataRequired {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_CauseOfDeathDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the cause of death.
        /// </summary>
        public static string ParticipantModel_Error_CauseOfDeathRequired {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_CauseOfDeathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please also enter the date the BCG vaccine was given.
        /// </summary>
        public static string ParticipantModel_Error_FollowUpWIthoutBCGDate {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_FollowUpWIthoutBCGDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight has changed too dramatically from birth ({0}g).
        /// </summary>
        public static string ParticipantModel_Error_LastWeightChange {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_LastWeightChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mother&apos;s BCG scar status is required.
        /// </summary>
        public static string ParticipantModel_Error_MaternalBcgRequired {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_MaternalBcgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the date of enrolment in the study.
        /// </summary>
        public static string ParticipantModel_Error_RegistrationDate {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the time of enrolment in the study.
        /// </summary>
        public static string ParticipantModel_Error_RegistrationDateTime {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_RegistrationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date of attempted contact.
        /// </summary>
        public static string ParticipantModel_Error_UncontactableWithoutAttempt {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_UncontactableWithoutAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of last weight cannot be after the date of death or last known contact.
        /// </summary>
        public static string ParticipantModel_Error_WeightAfterLastContact {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_WeightAfterLastContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the weight in grams.
        /// </summary>
        public static string ParticipantModel_Error_WeightNotFound {
            get {
                return ResourceManager.GetString("ParticipantModel_Error_WeightNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at 28 days of age.
        /// </summary>
        public static string ParticipantUpdateView_Label_28days {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_28days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG induration or papule or pustule.
        /// </summary>
        public static string ParticipantUpdateView_Label_BcgInduration {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_BcgInduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at the time of death.
        /// </summary>
        public static string ParticipantUpdateView_Label_Death {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of death.
        /// </summary>
        public static string ParticipantUpdateView_Label_DeathDate {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date/time of death.
        /// </summary>
        public static string ParticipantUpdateView_Label_DeathDateTime {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_DeathDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at the time of discharge.
        /// </summary>
        public static string ParticipantUpdateView_Label_Discharge {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_Discharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of last contact.
        /// </summary>
        public static string ParticipantUpdateView_Label_LastContactDate {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_LastContactDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date/time of last contact.
        /// </summary>
        public static string ParticipantUpdateView_Label_LastContactDateTime {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_LastContactDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (grams).
        /// </summary>
        public static string ParticipantUpdateView_Label_Weight {
            get {
                return ResourceManager.GetString("ParticipantUpdateView_Label_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close without saving changes (to save, click cancel and then fix the errors)?.
        /// </summary>
        public static string ParticipantUpdateVM_Confirm_Close {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Confirm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window (without saving).
        /// </summary>
        public static string ParticipantUpdateVM_Confirm_Close_Title {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Confirm_Close_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save before closing?.
        /// </summary>
        public static string ParticipantUpdateVM_Confirm_SaveChanges {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Confirm_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string ParticipantUpdateVM_Confirm_SaveChanges_Title {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Confirm_SaveChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ParticipantUpdateVM_ControlArm {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_ControlArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Participant (Blow Trial ID:{0}).
        /// </summary>
        public static string ParticipantUpdateVM_DisplayName {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to death.
        /// </summary>
        public static string ParticipantUpdateVM_Error_Death {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select whether the patient is {0} to have died or survived.
        /// </summary>
        public static string ParticipantUpdateVM_Error_DiedAfterDischargeRequired {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_DiedAfterDischargeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to known.
        /// </summary>
        public static string ParticipantUpdateVM_Error_Known {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likely.
        /// </summary>
        public static string ParticipantUpdateVM_Error_Likely {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_Likely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select whether {0} is known or suspected.
        /// </summary>
        public static string ParticipantUpdateVM_Error_PostDischargeOutcomeRequired {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_PostDischargeOutcomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survival.
        /// </summary>
        public static string ParticipantUpdateVM_Error_Survival {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Error_Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention.
        /// </summary>
        public static string ParticipantUpdateVM_InterventionArm {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_InterventionArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Phone.
        /// </summary>
        public static string ParticipantUpdateVM_NoPhone {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_NoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or BCG not given.
        /// </summary>
        public static string ParticipantUpdateVM_Option_BcgPapuleNull {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Option_BcgPapuleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG given to a patient in the control arm! A violation {0} logged..
        /// </summary>
        public static string ParticipantUpdateVM_Warning_BcgInControl {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Warning_BcgInControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been.
        /// </summary>
        public static string ParticipantUpdateVM_Warning_BcgInControl_HasBeen {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Warning_BcgInControl_HasBeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be.
        /// </summary>
        public static string ParticipantUpdateVM_Warning_BcgInControl_WillBee {
            get {
                return ResourceManager.GetString("ParticipantUpdateVM_Warning_BcgInControl_WillBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial will commence with this installation.
        /// </summary>
        public static string PreviouslyRandomisedOptions_False {
            get {
                return ResourceManager.GetString("PreviouslyRandomisedOptions_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients have been randomised by envelope.
        /// </summary>
        public static string PreviouslyRandomisedOptions_True {
            get {
                return ResourceManager.GetString("PreviouslyRandomisedOptions_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Protocol Violation.
        /// </summary>
        public static string ProtocolViolationVM_Edit {
            get {
                return ResourceManager.GetString("ProtocolViolationVM_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string ProtocolViolationVM_Major {
            get {
                return ResourceManager.GetString("ProtocolViolationVM_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string ProtocolViolationVM_Minor {
            get {
                return ResourceManager.GetString("ProtocolViolationVM_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Protocol Violation.
        /// </summary>
        public static string ProtocolViolationVM_Register {
            get {
                return ResourceManager.GetString("ProtocolViolationVM_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages On Randomisation.
        /// </summary>
        public static string RandomisedMessagesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RandomisedMessagesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please NO BCG while in NICU..
        /// </summary>
        public static string RandomisingMessages_DefaultControl {
            get {
                return ResourceManager.GetString("RandomisingMessages_DefaultControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give {0} as soon as possible..
        /// </summary>
        public static string RandomisingMessages_DefaultIntervention {
            get {
                return ResourceManager.GetString("RandomisingMessages_DefaultIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discharge from {0}.
        /// </summary>
        public static string RandomisingMessages_DischargeFrom {
            get {
                return ResourceManager.GetString("RandomisingMessages_DischargeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOSPITAL.
        /// </summary>
        public static string RandomisingMessages_Hospital {
            get {
                return ResourceManager.GetString("RandomisingMessages_Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICU or Level 2 Nursery.
        /// </summary>
        public static string RandomisingMessages_NICU {
            get {
                return ResourceManager.GetString("RandomisingMessages_NICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background colour must contrast with the error colour (red).
        /// </summary>
        public static string StudySiteDataModel_Error_BackgroundAndErrorMatch {
            get {
                return ResourceManager.GetString("StudySiteDataModel_Error_BackgroundAndErrorMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a colour.
        /// </summary>
        public static string StudySiteDataModel_Error_NoColour {
            get {
                return ResourceManager.GetString("StudySiteDataModel_Error_NoColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrospectively add data unless site is a data collecting site.
        /// </summary>
        public static string StudySiteDataModel_Error_PatientsPreviouslyRandomisedNotRelevant {
            get {
                return ResourceManager.GetString("StudySiteDataModel_Error_PatientsPreviouslyRandomisedNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text colour must contrast with the background colour.
        /// </summary>
        public static string StudySiteDataModel_Error_TextAndBackgroundMatch {
            get {
                return ResourceManager.GetString("StudySiteDataModel_Error_TextAndBackgroundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each site identifier must be unique.
        /// </summary>
        public static string StudySitesModel_Error_DuplicateId {
            get {
                return ResourceManager.GetString("StudySitesModel_Error_DuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an exact multiple of {0}.
        /// </summary>
        public static string StudySitesModel_Error_InvalidMultiple {
            get {
                return ResourceManager.GetString("StudySitesModel_Error_InvalidMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id range overlaps with the Id range for another site.
        /// </summary>
        public static string StudySitesModel_Error_OverlappingIdRanges {
            get {
                return ResourceManager.GetString("StudySitesModel_Error_OverlappingIdRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate Sites.
        /// </summary>
        public static string StudySitesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("StudySitesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for all enrolled participants.
        /// </summary>
        public static string TableOptions_Participant {
            get {
                return ResourceManager.GetString("TableOptions_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All protocol violations.
        /// </summary>
        public static string TableOptions_ProtocolViolations {
            get {
                return ResourceManager.GetString("TableOptions_ProtocolViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening log.
        /// </summary>
        public static string TableOptions_ScreenedPatients {
            get {
                return ResourceManager.GetString("TableOptions_ScreenedPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 days old ({0:g}).
        /// </summary>
        public static string TimeInterval_28days {
            get {
                return ResourceManager.GetString("TimeInterval_28days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date contact was attempted.
        /// </summary>
        public static string UnsuccessfulFollowUpModel_Error_AttemptedDateRequired {
            get {
                return ResourceManager.GetString("UnsuccessfulFollowUpModel_Error_AttemptedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG-Moreau(Brazil).
        /// </summary>
        public static string Vaccine_BcgBrazil {
            get {
                return ResourceManager.GetString("Vaccine_BcgBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG-Japan.
        /// </summary>
        public static string Vaccine_BcgJapan {
            get {
                return ResourceManager.GetString("Vaccine_BcgJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG-Danish.
        /// </summary>
        public static string Vaccine_DanishBcg {
            get {
                return ResourceManager.GetString("Vaccine_DanishBcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG-Green Signal.
        /// </summary>
        public static string Vaccine_GreenSignalBcg {
            get {
                return ResourceManager.GetString("Vaccine_GreenSignalBcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hep B.
        /// </summary>
        public static string Vaccine_HepB {
            get {
                return ResourceManager.GetString("Vaccine_HepB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPV (oral polio).
        /// </summary>
        public static string Vaccine_Opv {
            get {
                return ResourceManager.GetString("Vaccine_Opv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCG-India.
        /// </summary>
        public static string Vaccine_RussianBcg {
            get {
                return ResourceManager.GetString("Vaccine_RussianBcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the date of administration.
        /// </summary>
        public static string VaccineAdministeredModel_Error_NoAdminDate {
            get {
                return ResourceManager.GetString("VaccineAdministeredModel_Error_NoAdminDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a vaccine.
        /// </summary>
        public static string VaccineAdministeredModel_Error_NoVaccine {
            get {
                return ResourceManager.GetString("VaccineAdministeredModel_Error_NoVaccine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 type of BCG can be given per patient.
        /// </summary>
        public static string VaccineAdministeredVM_DualBcg {
            get {
                return ResourceManager.GetString("VaccineAdministeredVM_DualBcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same vaccine cannot be given twice.
        /// </summary>
        public static string VaccineAdministeredVM_DuplicateVaccine {
            get {
                return ResourceManager.GetString("VaccineAdministeredVM_DuplicateVaccine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major - Other.
        /// </summary>
        public static string ViolationTypeOption_MajorOther {
            get {
                return ResourceManager.GetString("ViolationTypeOption_MajorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major - Randomised on incorrect weight or gender.
        /// </summary>
        public static string ViolationTypeOption_MajorWrongAllocation {
            get {
                return ResourceManager.GetString("ViolationTypeOption_MajorWrongAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major - Wrong treatment applied.
        /// </summary>
        public static string ViolationTypeOption_MajorWrongTreatment {
            get {
                return ResourceManager.GetString("ViolationTypeOption_MajorWrongTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        public static string ViolationTypeOption_Minor {
            get {
                return ResourceManager.GetString("ViolationTypeOption_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WizardView_Button_Cancel {
            get {
                return ResourceManager.GetString("WizardView_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string WizardView_Button_Finish {
            get {
                return ResourceManager.GetString("WizardView_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string WizardView_Button_MoveNext {
            get {
                return ResourceManager.GetString("WizardView_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string WizardView_Button_MovePrevious {
            get {
                return ResourceManager.GetString("WizardView_Button_MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string WizardView_Header_Steps {
            get {
                return ResourceManager.GetString("WizardView_Header_Steps", resourceCulture);
            }
        }
    }
}
